"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "ur"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Comprehensive translations for English and Urdu
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.processes": "Processes",
    "nav.proposals": "Proposals",
    "nav.budgets": "Budgets",
    "nav.discussions": "Discussions",
    "nav.about": "About",
    
    // Common
    "common.login": "Login",
    "common.register": "Register",
    "common.logout": "Logout",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    
    // Auth
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.fullName": "Full Name",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.forgotPassword": "Forgot Password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    
    // Home page
    "home.hero.title": "Your Voice Matters in Pakistan's Democracy",
    "home.hero.subtitle": "Hum Awaz empowers citizens to participate in democratic processes, deliberate on public issues, and contribute to collective decision-making.",
    "home.hero.explore": "Explore Active Processes",
    "home.hero.learnMore": "Learn More",
    
    // Processes
    "processes.title": "Participation Processes",
    "processes.subtitle": "Explore and participate in democratic processes across Pakistan",
    "processes.newProcess": "Start a New Process",
    "processes.search": "Search processes...",
    "processes.filters": "Filters",
    "processes.all": "All Processes",
    "processes.active": "Active",
    "processes.upcoming": "Upcoming",
    "processes.completed": "Completed",
    "processes.participate": "Participate",
    "processes.participants": "participants",
    "processes.progress": "Progress",
    "processes.ends": "Ends",
    
    // Process phases
    "phase.discussion": "Discussion",
    "phase.voting": "Voting",
    "phase.proposal": "Proposal",
    "phase.implementation": "Implementation",
    
    // Categories
    "category.education": "Education",
    "category.infrastructure": "Infrastructure",
    "category.healthcare": "Healthcare",
    "category.environment": "Environment",
    "category.economy": "Economy",
    "category.governance": "Governance",
    "category.other": "Other",
    "category.urbanPlanning": "Urban Planning",
    
    // Status
    "status.draft": "Draft",
    "status.active": "Active",
    "status.closed": "Closed",
    "status.completed": "Completed",
    "status.pending": "Pending",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.implemented": "Implemented",
    
    // Features
    "features.inclusive.title": "Inclusive Participation",
    "features.inclusive.description": "Designed for all Pakistanis regardless of background or technical expertise",
    "features.transparent.title": "Transparent Processes",
    "features.transparent.description": "Follow proposals from submission to implementation",
    "features.secure.title": "Secure Voting",
    "features.secure.description": "Make your voice heard with confidence",
    
    // Stats
    "stats.title": "Participation Statistics",
    "stats.subtitle": "See how Pakistanis are engaging with democratic processes",
    
    // How to participate
    "howTo.title": "How to Participate",
    "howTo.subtitle": "Getting started with Hum Awaz is easy",
    
    // Participatory Budgeting
    "participatoryBudgets": "Participatory Budgets",
    "participatoryBudgetsDescription": "Vote on how your government allocates public funds across different categories and priorities",
    "createBudget": "Create Budget",
    "createNewBudget": "Create New Budget",
    "createBudgetDescription": "Set up a new participatory budget for citizen input on fund allocation",
    "backToBudgets": "Back to Budgets",
    "budgetList": "Budget List",
    "noBudgets": "No Budgets Yet",
    "noBudgetsDescription": "Start by creating the first participatory budget for citizen engagement",
    "createFirstBudget": "Create First Budget",
    "totalBudgets": "Total Budgets",
    "activeBudgets": "Active Budgets", 
    "totalValue": "Total Value",
    "thisYear": "This Year",
    "complete": "complete",
    "viewDetails": "View Details",
    "basicInformation": "Basic Information",
    "linkedProcess": "Linked Process",
    "optional": "optional",
    "selectProcess": "Select Process",
    "title": "Title",
    "description": "Description",
    "totalAmount": "Total Amount",
    "currency": "Currency", 
    "fiscalYear": "Fiscal Year",
    "startDate": "Start Date",
    "endDate": "End Date",
    "budgetCategories": "Budget Categories",
    "addCategory": "Add Category",
    "noCategoriesYet": "No categories added yet",
    "addFirstCategory": "Add First Category",
    "category": "Category",
    "name": "Name",
    "icon": "Icon",
    "color": "Color",
    "suggestedAmount": "Suggested Amount",
    "maxAmount": "Maximum Amount",
    "creating": "Creating...",
    "titleRequired": "Title is required",
    "descriptionRequired": "Description is required",
    "totalAmountRequired": "Total amount must be greater than 0",
    "datesRequired": "Start and end dates are required",
    "endDateAfterStart": "End date must be after start date",
    "categoriesRequired": "At least one category is required",
    "categoryNameRequired": "Category name is required",
    "categorySuggestedAmountRequired": "Category suggested amount is required",
    "totalSuggestedExceedsBudget": "Total suggested amounts exceed the budget",
    "errorCreatingBudget": "Error creating budget. Please try again.",
    "voting": "Voting",
    "approved": "Approved",
    "budgetNotFound": "Budget Not Found",
    "updateVote": "Update Vote",
    "voteOnBudget": "Vote on Budget",
    "allocateBudget": "Allocate Budget",
    "allocateBudgetDescription": "Distribute the total budget across categories based on your priorities",
    "remaining": "Remaining",
    "budgetExceeded": "Budget exceeded! Please reduce allocations.",
    "suggested": "Suggested",
    "yourAllocation": "Your Allocation",
    "useSuggested": "Use Suggested",
    "averageAllocation": "Average Allocation",
    "totalVotes": "Total Votes",
    "yourVote": "Your Vote",
    "notVoted": "Not Voted",
    "useSuggestedAmounts": "Use Suggested Amounts",
    "saving": "Saving...",
    "submitVote": "Submit Vote",
    "budgetStats": "Budget Statistics",
    "totalParticipants": "Total Participants",
    "categories": "Categories",
    "timeRemaining": "Time Remaining",
    "yourParticipation": "Your Participation",
    "votingStatus": "Voting Status",
    "voted": "Voted",
    "totalAllocated": "Total Allocated",
    "lastUpdated": "Last Updated",
    "never": "Never",
    "voteSubmittedSuccessfully": "Vote submitted successfully!",
    "errorSavingVote": "Error saving vote. Please try again.",
    "ends": "Ends",
    
    // Enhanced Process Types (Decidim & Polis inspired)
    "processType.consultation": "Government Consultation",
    "processType.initiative": "Citizen Initiative",
    "processType.assembly": "Deliberative Assembly",
    "processType.poll": "Opinion Poll",
    "processType.petition": "Petition",
    "processType.budget": "Participatory Budget",
    "processType.debate": "Public Debate",
    
    "processScope.federal": "Federal",
    "processScope.provincial": "Provincial",
    "processScope.city": "City",
    "processScope.district": "District",
    "processScope.community": "Community",
    
    "participationMethod.open": "Open to All",
    "participationMethod.invited": "By Invitation",
    "participationMethod.random_selection": "Random Selection",
    "participationMethod.application": "By Application",
    
    "visibility.public": "Public",
    "visibility.restricted": "Restricted",
    "visibility.private": "Private",
    
    "signatureThreshold": "Signature Threshold",
    "currentSignatures": "Current Signatures",
    "signProcess": "Sign Process",
    "removeSignature": "Remove Signature",
    "signatureProgress": "Signature Progress",
    "signatureDeadline": "Signature Deadline",
    "governmentResponse": "Government Response",
    "responseRequired": "Response Required",
    "responseDeadline": "Response Deadline",
    "awaitingResponse": "Awaiting Government Response",
    "thresholdMet": "Threshold Met!",
    "signatureComment": "Comment (Optional)",
    "verificationRequired": "Verification Required",
    
    "meetingType.in_person": "In Person",
    "meetingType.online": "Online",
    "meetingType.hybrid": "Hybrid",
    
    "meetingStatus.upcoming": "Upcoming",
    "meetingStatus.ongoing": "Ongoing",
    "meetingStatus.completed": "Completed",
    "meetingStatus.cancelled": "Cancelled",
    
    "registerForMeeting": "Register for Meeting",
    "meetingRegistration": "Meeting Registration",
    "maxAttendees": "Maximum Attendees",
    "registrationDeadline": "Registration Deadline",
    "onlineMeetingUrl": "Online Meeting URL",
    "agenda": "Agenda",
    "minutes": "Minutes",
    
    "userRole.citizen": "Citizen",
    "userRole.admin": "Admin",
    "userRole.moderator": "Moderator",
    "userRole.facilitator": "Facilitator",
    "userRole.observer": "Observer",
    
    "followProcess": "Follow Process",
    "unfollowProcess": "Unfollow Process",
    "followers": "Followers",
    "notificationPreferences": "Notification Preferences",
    "emailNotifications": "Email Notifications",
    "pushNotifications": "Push Notifications",

    // Admin Dashboard
    "admin.title": "Admin Panel",
    "admin.overview": "Overview",
    "admin.proposals": "Proposals",
    "admin.processes": "Processes",
    "admin.backToDashboard": "Back to Dashboard",
    "admin.dashboardTitle": "Admin Dashboard",
    "admin.dashboardDescription": "Manage processes, proposals, and platform activity.",
    "admin.pendingReview": "Pending Review",
    "admin.proposalsAwaitingAction": "Proposals awaiting action",
    "admin.activeProcesses": "Active Processes",
    "admin.total": "total",
    "admin.totalProposals": "Total Proposals",
    "admin.approved": "approved",
    "admin.totalUsers": "Total Users",
    "admin.votesCast": "votes cast",
    "admin.proposalBreakdown": "Proposal Breakdown",
    "admin.proposalBreakdownDesc": "Current status of all proposals",
    "admin.processBreakdown": "Process Breakdown",
    "admin.processBreakdownDesc": "Current status of all processes",
    "admin.underReview": "Under Review",
    "admin.implemented": "Implemented",
    "admin.manageProposals": "Manage Proposals",
    "admin.manageProcesses": "Manage Processes",
    "admin.recentPendingProposals": "Proposals Needing Review",
    "admin.recentPendingDesc": "Latest proposals awaiting your review",
    "admin.reviewAll": "Review All Proposals",
    "admin.proposalManagement": "Proposal Management",
    "admin.proposalManagementDesc": "Review, approve, or reject citizen proposals.",
    "admin.filterByStatus": "Filter by status",
    "admin.allStatuses": "All Statuses",
    "admin.selected": "selected",
    "admin.approveSelected": "Approve",
    "admin.rejectSelected": "Reject",
    "admin.noProposals": "No proposals found.",
    "admin.proposalTitle": "Title",
    "admin.process": "Process",
    "admin.author": "Author",
    "admin.status": "Status",
    "admin.votes": "Votes",
    "admin.actions": "Actions",
    "admin.approveProposals": "Approve Proposals",
    "admin.rejectProposals": "Reject Proposals",
    "admin.changeStatus": "Change Status",
    "admin.approveConfirm": "Are you sure you want to approve the selected proposals?",
    "admin.rejectConfirm": "Are you sure you want to reject the selected proposals? A reason is required.",
    "admin.statusConfirm": "Select the new status for this item.",
    "admin.selectStatus": "Select status",
    "admin.reasonPlaceholder": "Reason (optional)",
    "admin.rejectReasonPlaceholder": "Reason for rejection (required)",
    "admin.reasonRequired": "A reason is required for rejection.",
    "admin.proposalsApproved": "Proposals approved successfully.",
    "admin.proposalsRejected": "Proposals rejected successfully.",
    "admin.statusUpdated": "Status updated successfully.",
    "admin.processManagement": "Process Management",
    "admin.processManagementDesc": "Manage the lifecycle of democratic processes.",
    "admin.noProcesses": "No processes found.",
    "admin.processTitle": "Title",
    "admin.category": "Category",
    "admin.timeline": "Timeline",
    "admin.participants": "Participants",
    "admin.changeProcessStatus": "Change Process Status",
    "admin.processStatusConfirm": "Select the new status for this process.",
    "admin.updateStatus": "Update Status",

    // Admin User Management
    "admin.users": "Users",
    "admin.userManagement": "User Management",
    "admin.userManagementDesc": "Create users, assign roles, and manage access.",
    "admin.createUser": "Create User",
    "admin.createUserDesc": "Create a new user account with email and password.",
    "admin.searchUsers": "Search by name or email...",
    "admin.noUsersFound": "No users found.",
    "admin.userName": "Name",
    "admin.userEmail": "Email",
    "admin.userRoles": "Roles",
    "admin.lastSignIn": "Last Sign In",
    "admin.fullName": "Full Name",
    "admin.fullNamePlaceholder": "Enter full name",
    "admin.password": "Password",
    "admin.passwordPlaceholder": "Minimum 6 characters",
    "admin.emailPasswordRequired": "Email and password are required.",
    "admin.userCreated": "User created successfully.",
    "admin.userDeleted": "User deleted successfully.",
    "admin.assignRole": "Assign Role",
    "admin.removeRole": "Remove Role",
    "admin.assignRoleDesc": "Assign a role to {user}.",
    "admin.removeRoleDesc": "Remove a role from {user}.",
    "admin.selectRole": "Select role",
    "admin.roleAssigned": "Role assigned successfully.",
    "admin.roleRemoved": "Role removed successfully.",
    "admin.deleteUser": "Delete User",
    "admin.deleteUserConfirm": "Are you sure you want to permanently delete {user}? This cannot be undone.",
    "admin.govAdmin": "Admin",
    "admin.moderator": "Moderator",
    "admin.facilitator": "Facilitator",
    "admin.citizen": "Citizen",
  },
  ur: {
    // Navigation
    "nav.home": "ہوم",
    "nav.processes": "عمل",
    "nav.proposals": "تجاویز",
    "nav.budgets": "بجٹ",
    "nav.discussions": "بحث",
    "nav.about": "ہمارے بارے میں",
    
    // Common
    "common.login": "لاگ ان",
    "common.register": "رجسٹر",
    "common.logout": "لاگ آؤٹ",
    "common.submit": "جمع کرائیں",
    "common.cancel": "منسوخ کریں",
    "common.save": "محفوظ کریں",
    "common.edit": "ترمیم",
    "common.delete": "حذف کریں",
    "common.back": "واپس",
    "common.next": "اگلا",
    "common.previous": "پچھلا",
    "common.loading": "لوڈ ہو رہا ہے...",
    "common.error": "غلطی",
    "common.success": "کامیاب",
    
    // Auth
    "auth.email": "ای میل",
    "auth.password": "پاس ورڈ",
    "auth.confirmPassword": "پاس ورڈ کی تصدیق",
    "auth.fullName": "پورا نام",
    "auth.signIn": "سائن ان",
    "auth.signUp": "سائن اپ",
    "auth.forgotPassword": "پاس ورڈ بھول گئے؟",
    "auth.noAccount": "اکاؤنٹ نہیں ہے؟",
    "auth.hasAccount": "پہلے سے اکاؤنٹ ہے؟",
    
    // Home page
    "home.hero.title": "پاکستان کی جمہوریت میں آپ کی آواز اہم ہے",
    "home.hero.subtitle": "ہم آواز شہریوں کو جمہوری عمل میں حصہ لینے، عوامی مسائل پر غور کرنے اور اجتماعی فیصلہ سازی میں حصہ لینے کی طاقت دیتا ہے۔",
    "home.hero.explore": "فعال عمل دیکھیں",
    "home.hero.learnMore": "مزید جانیں",
    
    // Processes
    "processes.title": "شرکت کے عمل",
    "processes.subtitle": "پاکستان بھر میں جمہوری عمل کو دریافت کریں اور ان میں حصہ لیں",
    "processes.newProcess": "نیا عمل شروع کریں",
    "processes.search": "عمل تلاش کریں...",
    "processes.filters": "فلٹرز",
    "processes.all": "تمام عمل",
    "processes.active": "فعال",
    "processes.upcoming": "آنے والے",
    "processes.completed": "مکمل",
    "processes.participate": "حصہ لیں",
    "processes.participants": "شرکاء",
    "processes.progress": "ترقی",
    "processes.ends": "ختم ہوتا ہے",
    
    // Process phases
    "phase.discussion": "بحث",
    "phase.voting": "ووٹنگ",
    "phase.proposal": "تجویز",
    "phase.implementation": "نفاذ",
    
    // Categories
    "category.education": "تعلیم",
    "category.infrastructure": "انفراسٹرکچر",
    "category.healthcare": "صحت کی دیکھ بھال",
    "category.environment": "ماحول",
    "category.economy": "معیشت",
    "category.governance": "حکمرانی",
    "category.other": "دیگر",
    "category.urbanPlanning": "شہری منصوبہ بندی",
    
    // Status
    "status.draft": "مسودہ",
    "status.active": "فعال",
    "status.closed": "بند",
    "status.completed": "مکمل",
    "status.pending": "زیر التواء",
    "status.approved": "منظور شدہ",
    "status.rejected": "مسترد",
    "status.implemented": "نافذ",
    
    // Features
    "features.inclusive.title": "شمولیت کی شرکت",
    "features.inclusive.description": "تمام پاکستانیوں کے لیے ڈیزائن کیا گیا ہے، پس منظر یا تکنیکی مہارت سے قطع نظر",
    "features.transparent.title": "شفاف عمل",
    "features.transparent.description": "جمع کرائی سے نفاذ تک تجاویز کی پیروی کریں",
    "features.secure.title": "محفوظ ووٹنگ",
    "features.secure.description": "اعتماد کے ساتھ اپنی آواز سنائیں",
    
    // Stats
    "stats.title": "شرکت کے اعداد و شمار",
    "stats.subtitle": "دیکھیں کہ پاکستانی جمہوری عمل میں کیسے شامل ہو رہے ہیں",
    
    // How to participate
    "howTo.title": "کیسے حصہ لیں",
    "howTo.subtitle": "ہم آواز کے ساتھ شروع کرنا آسان ہے",
    
    // Participatory Budgeting
    "participatoryBudgets": "شراکتی بجٹ",
    "participatoryBudgetsDescription": "مختلف کیٹگریز اور ترجیحات میں حکومت کے پبلک فنڈز کی تقسیم پر ووٹ دیں",
    "createBudget": "بجٹ بنائیں",
    "createNewBudget": "نیا بجٹ بنائیں", 
    "createBudgetDescription": "فنڈز کی تقسیم پر شہریوں کی رائے کے لیے نیا شراکتی بجٹ سیٹ اپ کریں",
    "backToBudgets": "بجٹس پر واپس",
    "budgetList": "بجٹ فہرست",
    "noBudgets": "ابھی کوئی بجٹ نہیں",
    "noBudgetsDescription": "شہری شمولیت کے لیے پہلا شراکتی بجٹ بنا کر شروع کریں",
    "createFirstBudget": "پہلا بجٹ بنائیں",
    "totalBudgets": "کل بجٹس",
    "activeBudgets": "فعال بجٹس",
    "totalValue": "کل قیمت",
    "thisYear": "اس سال",
    "complete": "مکمل",
    "viewDetails": "تفصیلات دیکھیں",
    "basicInformation": "بنیادی معلومات",
    "linkedProcess": "منسلک عمل",
    "optional": "اختیاری",
    "selectProcess": "عمل منتخب کریں",
    "title": "عنوان",
    "description": "تفصیل",
    "totalAmount": "کل رقم",
    "currency": "کرنسی",
    "fiscalYear": "مالی سال",
    "startDate": "شروع کی تاریخ",
    "endDate": "ختم کی تاریخ",
    "budgetCategories": "بجٹ کیٹگریز",
    "addCategory": "کیٹگری شامل کریں",
    "noCategoriesYet": "ابھی کوئی کیٹگری شامل نہیں",
    "addFirstCategory": "پہلی کیٹگری شامل کریں",
    "category": "کیٹگری",
    "name": "نام",
    "icon": "آئیکن",
    "color": "رنگ",
    "suggestedAmount": "تجویز کردہ رقم",
    "maxAmount": "زیادہ سے زیادہ رقم",
    "creating": "بنایا جا رہا ہے...",
    "titleRequired": "عنوان ضروری ہے",
    "descriptionRequired": "تفصیل ضروری ہے",
    "totalAmountRequired": "کل رقم صفر سے زیادہ ہونی چاہیے",
    "datesRequired": "شروع اور ختم کی تاریخیں ضروری ہیں",
    "endDateAfterStart": "ختم کی تاریخ شروع کی تاریخ کے بعد ہونی چاہیے",
    "categoriesRequired": "کم از کم ایک کیٹگری ضروری ہے",
    "categoryNameRequired": "کیٹگری کا نام ضروری ہے",
    "categorySuggestedAmountRequired": "کیٹگری کی تجویز کردہ رقم ضروری ہے",
    "totalSuggestedExceedsBudget": "کل تجویز کردہ رقم بجٹ سے زیادہ ہے",
    "errorCreatingBudget": "بجٹ بناتے وقت خرابی۔ دوبارہ کوشش کریں۔",
    "voting": "ووٹنگ",
    "approved": "منظور شدہ",
    "budgetNotFound": "بجٹ نہیں ملا",
    "updateVote": "ووٹ اپ ڈیٹ کریں",
    "voteOnBudget": "بجٹ پر ووٹ دیں",
    "allocateBudget": "بجٹ تقسیم کریں",
    "allocateBudgetDescription": "اپنی ترجیحات کی بنیاد پر کل بجٹ کو کیٹگریز میں تقسیم کریں",
    "remaining": "باقی",
    "budgetExceeded": "بجٹ ختم! براہ کرم تقسیم کم کریں۔",
    "suggested": "تجویز کردہ",
    "yourAllocation": "آپ کی تقسیم",
    "useSuggested": "تجویز کردہ استعمال کریں",
    "averageAllocation": "اوسط تقسیم",
    "totalVotes": "کل ووٹس",
    "yourVote": "آپ کا ووٹ",
    "notVoted": "ووٹ نہیں دیا",
    "useSuggestedAmounts": "تجویز کردہ رقم استعمال کریں",
    "saving": "محفوظ کر رہے ہیں...",
    "submitVote": "ووٹ جمع کریں",
    "budgetStats": "بجٹ کے اعداد و شمار",
    "totalParticipants": "کل شرکا",
    "categories": "کیٹگریز",
    "timeRemaining": "باقی وقت",
    "yourParticipation": "آپ کی شرکت",
    "votingStatus": "ووٹنگ کی صورتحال",
    "voted": "ووٹ دیا",
    "totalAllocated": "کل تقسیم شدہ",
    "lastUpdated": "آخری اپ ڈیٹ",
    "never": "کبھی نہیں",
    "voteSubmittedSuccessfully": "ووٹ کامیابی سے جمع ہوا!",
    "errorSavingVote": "ووٹ محفوظ کرتے وقت خرابی۔ دوبارہ کوشش کریں۔",
    "ends": "ختم",
    
    // Enhanced Process Types (Decidim & Polis inspired)
    "processType.consultation": "حکومتی مشاورت",
    "processType.initiative": "شہری اقدام",
    "processType.assembly": "بحث و مذاکرہ کی اسمبلی",
    "processType.poll": "رائے شماری",
    "processType.petition": "درخواست",
    "processType.budget": "شراکتی بجٹ",
    "processType.debate": "عوامی بحث",
    
    "processScope.federal": "وفاقی",
    "processScope.provincial": "صوبائی",
    "processScope.city": "شہری",
    "processScope.district": "ضلعی",
    "processScope.community": "کمیونٹی",
    
    "participationMethod.open": "سب کے لیے کھلا",
    "participationMethod.invited": "دعوت پر",
    "participationMethod.random_selection": "بے ترتیب انتخاب",
    "participationMethod.application": "درخواست کے ذریعے",
    
    "visibility.public": "عوامی",
    "visibility.restricted": "محدود",
    "visibility.private": "نجی",
    
    "signatureThreshold": "دستخط کی حد",
    "currentSignatures": "موجودہ دستخط",
    "signProcess": "عمل پر دستخط",
    "removeSignature": "دستخط ہٹائیں",
    "signatureProgress": "دستخط کی پیش قدمی",
    "signatureDeadline": "دستخط کی آخری تاریخ",
    "governmentResponse": "حکومتی جواب",
    "responseRequired": "جواب درکار",
    "responseDeadline": "جواب کی آخری تاریخ",
    "awaitingResponse": "حکومتی جواب کا انتظار",
    "thresholdMet": "حد پوری ہوگئی!",
    "signatureComment": "تبصرہ (اختیاری)",
    "verificationRequired": "تصدیق درکار",
    
    "meetingType.in_person": "ذاتی طور پر",
    "meetingType.online": "آن لائن",
    "meetingType.hybrid": "ملا جلا",
    
    "meetingStatus.upcoming": "آنے والا",
    "meetingStatus.ongoing": "جاری",
    "meetingStatus.completed": "مکمل",
    "meetingStatus.cancelled": "منسوخ",
    
    "registerForMeeting": "میٹنگ کے لیے رجسٹر",
    "meetingRegistration": "میٹنگ رجسٹریشن",
    "maxAttendees": "زیادہ سے زیادہ شرکاء",
    "registrationDeadline": "رجسٹریشن کی آخری تاریخ",
    "onlineMeetingUrl": "آن لائن میٹنگ URL",
    "agenda": "ایجنڈا",
    "minutes": "کارروائی",
    
    "userRole.citizen": "شہری",
    "userRole.admin": "ایڈمن",
    "userRole.moderator": "ناظم",
    "userRole.facilitator": "سہولت کار",
    "userRole.observer": "مبصر",
    
    "followProcess": "عمل کو فالو کریں",
    "unfollowProcess": "عمل کو ان فالو کریں",
    "followers": "فالوورز",
    "notificationPreferences": "اطلاع کی ترجیحات",
    "emailNotifications": "ای میل اطلاعات",
    "pushNotifications": "پش اطلاعات",

    // Admin Dashboard
    "admin.title": "ایڈمن پینل",
    "admin.overview": "جائزہ",
    "admin.proposals": "تجاویز",
    "admin.processes": "عمل",
    "admin.backToDashboard": "ڈیش بورڈ پر واپس",
    "admin.dashboardTitle": "ایڈمن ڈیش بورڈ",
    "admin.dashboardDescription": "عمل، تجاویز، اور پلیٹ فارم سرگرمی کا انتظام کریں۔",
    "admin.pendingReview": "زیر جائزہ",
    "admin.proposalsAwaitingAction": "تجاویز کارروائی کے منتظر",
    "admin.activeProcesses": "فعال عمل",
    "admin.total": "کل",
    "admin.totalProposals": "کل تجاویز",
    "admin.approved": "منظور شدہ",
    "admin.totalUsers": "کل صارفین",
    "admin.votesCast": "ووٹ ڈالے گئے",
    "admin.proposalBreakdown": "تجاویز کی تقسیم",
    "admin.proposalBreakdownDesc": "تمام تجاویز کی موجودہ حیثیت",
    "admin.processBreakdown": "عمل کی تقسیم",
    "admin.processBreakdownDesc": "تمام عمل کی موجودہ حیثیت",
    "admin.underReview": "زیر جائزہ",
    "admin.implemented": "نافذ",
    "admin.manageProposals": "تجاویز کا انتظام",
    "admin.manageProcesses": "عمل کا انتظام",
    "admin.recentPendingProposals": "جائزے کی ضرورت والی تجاویز",
    "admin.recentPendingDesc": "آپ کے جائزے کے منتظر تازہ ترین تجاویز",
    "admin.reviewAll": "تمام تجاویز کا جائزہ لیں",
    "admin.proposalManagement": "تجاویز کا انتظام",
    "admin.proposalManagementDesc": "شہریوں کی تجاویز کا جائزہ لیں، منظور کریں، یا مسترد کریں۔",
    "admin.filterByStatus": "حیثیت کے مطابق فلٹر",
    "admin.allStatuses": "تمام حیثیتیں",
    "admin.selected": "منتخب",
    "admin.approveSelected": "منظور کریں",
    "admin.rejectSelected": "مسترد کریں",
    "admin.noProposals": "کوئی تجویز نہیں ملی۔",
    "admin.proposalTitle": "عنوان",
    "admin.process": "عمل",
    "admin.author": "مصنف",
    "admin.status": "حیثیت",
    "admin.votes": "ووٹ",
    "admin.actions": "اعمال",
    "admin.approveProposals": "تجاویز منظور کریں",
    "admin.rejectProposals": "تجاویز مسترد کریں",
    "admin.changeStatus": "حیثیت تبدیل کریں",
    "admin.approveConfirm": "کیا آپ واقعی منتخب تجاویز کو منظور کرنا چاہتے ہیں؟",
    "admin.rejectConfirm": "کیا آپ واقعی منتخب تجاویز کو مسترد کرنا چاہتے ہیں؟ وجہ ضروری ہے۔",
    "admin.statusConfirm": "اس آئٹم کی نئی حیثیت منتخب کریں۔",
    "admin.selectStatus": "حیثیت منتخب کریں",
    "admin.reasonPlaceholder": "وجہ (اختیاری)",
    "admin.rejectReasonPlaceholder": "مسترد کرنے کی وجہ (ضروری)",
    "admin.reasonRequired": "مسترد کرنے کے لیے وجہ ضروری ہے۔",
    "admin.proposalsApproved": "تجاویز کامیابی سے منظور ہو گئیں۔",
    "admin.proposalsRejected": "تجاویز کامیابی سے مسترد ہو گئیں۔",
    "admin.statusUpdated": "حیثیت کامیابی سے تبدیل ہو گئی۔",
    "admin.processManagement": "عمل کا انتظام",
    "admin.processManagementDesc": "جمہوری عمل کی زندگی کے چکر کا انتظام کریں۔",
    "admin.noProcesses": "کوئی عمل نہیں ملا۔",
    "admin.processTitle": "عنوان",
    "admin.category": "زمرہ",
    "admin.timeline": "ٹائم لائن",
    "admin.participants": "شرکاء",
    "admin.changeProcessStatus": "عمل کی حیثیت تبدیل کریں",
    "admin.processStatusConfirm": "اس عمل کی نئی حیثیت منتخب کریں۔",
    "admin.updateStatus": "حیثیت تبدیل کریں",

    // Admin User Management
    "admin.users": "صارفین",
    "admin.userManagement": "صارف انتظام",
    "admin.userManagementDesc": "صارفین بنائیں، کردار تفویض کریں، اور رسائی کا انتظام کریں۔",
    "admin.createUser": "صارف بنائیں",
    "admin.createUserDesc": "ای میل اور پاس ورڈ کے ساتھ نیا صارف اکاؤنٹ بنائیں۔",
    "admin.searchUsers": "نام یا ای میل سے تلاش کریں...",
    "admin.noUsersFound": "کوئی صارف نہیں ملا۔",
    "admin.userName": "نام",
    "admin.userEmail": "ای میل",
    "admin.userRoles": "کردار",
    "admin.lastSignIn": "آخری سائن ان",
    "admin.fullName": "پورا نام",
    "admin.fullNamePlaceholder": "پورا نام درج کریں",
    "admin.password": "پاس ورڈ",
    "admin.passwordPlaceholder": "کم از کم 6 حروف",
    "admin.emailPasswordRequired": "ای میل اور پاس ورڈ ضروری ہیں۔",
    "admin.userCreated": "صارف کامیابی سے بنایا گیا۔",
    "admin.userDeleted": "صارف کامیابی سے حذف ہو گیا۔",
    "admin.assignRole": "کردار تفویض کریں",
    "admin.removeRole": "کردار ہٹائیں",
    "admin.assignRoleDesc": "{user} کو کردار تفویض کریں۔",
    "admin.removeRoleDesc": "{user} سے کردار ہٹائیں۔",
    "admin.selectRole": "کردار منتخب کریں",
    "admin.roleAssigned": "کردار کامیابی سے تفویض ہو گیا۔",
    "admin.roleRemoved": "کردار کامیابی سے ہٹا دیا گیا۔",
    "admin.deleteUser": "صارف حذف کریں",
    "admin.deleteUserConfirm": "کیا آپ واقعی {user} کو مستقل طور پر حذف کرنا چاہتے ہیں؟ یہ واپس نہیں ہو سکتا۔",
    "admin.govAdmin": "ایڈمن",
    "admin.moderator": "ناظم",
    "admin.facilitator": "سہولت کار",
    "admin.citizen": "شہری",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    // Check for saved language preference
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
    // Or detect browser language
    else {
      const browserLang = navigator.language.split("-")[0]
      if (browserLang === "ur") setLanguage("ur")
      // Default to English if no match
    }
  }, [])

  // Save language preference when it changes
  useEffect(() => {
    localStorage.setItem("language", language)
    // Update document direction for RTL languages
    document.documentElement.dir = ["ur", "sd"].includes(language) ? "rtl" : "ltr"
  }, [language])

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
